// lib/main.dart

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';
import 'package:firebase_core/firebase_core.dart';
import 'core/services/storage_service.dart';
import 'core/services/notification_service.dart';
import 'core/services/fcm_service.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'app.dart';

void main() async {
  final widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);

  // 1. Cache SharedPreferences — all StorageService calls are sync after this.
  await StorageService.init();

  // 2. Initialise Firebase — must happen before runApp and before FCMService.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 3. System UI chrome.
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Color(0xFFE0F2FE),
      statusBarIconBrightness: Brightness.dark,
      systemNavigationBarColor: Color(0xFFE0F2FE),
      systemNavigationBarIconBrightness: Brightness.dark,
    ),
  );

  // 4. Start the app — everything below runs in parallel with the first frame.
  runApp(const App());

  // 5. Initialise notification channels and FCM token registration
  //    asynchronously so they don't delay the first frame.
  unawaited(NotificationService.instance.init());
  unawaited(FCMService.instance.init());

  // BackgroundLocationService is initialised inside SplashScreen.initState.
}